version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - 5432:5432
  backend:
    image: api-node:latest
    container_name: node-api
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
  frontend:
    image: nginx
    container_name: front
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - postgres
      - backend
