version: '3'

services:
  db-postgres:
    image: postgres:14-alpine
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432
  api-docker:
    image: api-node:latest
    container_name: node-api
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - db-postgres
