export { HOME } from "./home"
export { LOGIN } from "./login"
export { POPUP } from "./popup"
export { REGISTER } from "./register"
export { CUSTOMER } from "./customer"
export { DASHBOARD } from "./dashboard"
export { USER } from "./user"